server:
  port: 8082
spring:
  application:
    name: CITYS
  cloud:
    consul:
      host: 192.168.1.30
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}
